### ISSUE TITLE
Typo in index.html

### ISSUE THREAD

**Issue by rstephan** [fulldecent/system-bus-radio#46]
There is this part: "AM tuner at 1560 Hz". The k for Kilo is missing. It should be: "AM tuner at 1560 **kHz**".

Right?

**Comment by fulldecent** [comment]
I believe this was fixed, thank you. If you see one we missed, please reopen.

**Comment by rstephan** [comment]
Sorry.
No. It's here: docs/index.html, line 15. Still missing a little "k".

**Comment by fulldecent** [comment]
Aha, thank you, fixed at https://github.com/fulldecent/system-bus-radio/commit/bc9bc6c8c0336a04180c9bdb22f7b49ee28c2686
